### ISSUE TITLE
Bị lỗi block nvform 

### ISSUE THREAD

**Issue by aothunit** [nukeviet/module-nvform#13]
- Thêm câu hỏi mục chọn dữ liệu :  Lựa chọn thả xuống (selectbox) 
  phần mở rộng ko hiện ở phần block hiện ngoài trang chủ.
- Thêm câu hỏi mục chọn dữ liệu :  Tập tin đính kèm
  ko hiện ở phần block hiện ngoài trang chủ.
- Xem tóm tắt xuất hiện lỗi " Hệ thống không tìm thấy biểu mẫu nào theo như yêu cầu của bạn.
  Vui lòng liên hệ với quản trị để biết thêm thông tin. "

**Comment by mynukeviet** [comment]
> Xem tóm tắt xuất hiện lỗi " Hệ thống không tìm thấy biểu mẫu nào theo như yêu cầu của bạn. Vui lòng liên hệ với quản trị để biết thêm thông tin. "

Fixed: https://github.com/hongoctrien/module-nvform/commit/43ae4030d339a97ece884e83436d4e85d46cc6e6

**Comment by mynukeviet** [comment]
> Thêm câu hỏi mục chọn dữ liệu : Lựa chọn thả xuống (selectbox) phần mở rộng ko hiện ở phần block hiện ngoài trang chủ.
> 
> Thêm câu hỏi mục chọn dữ liệu : Tập tin đính kèm ko hiện ở phần block hiện ngoài trang chủ.

Fixed: https://github.com/hongoctrien/module-nvform/commit/435fe508f731158760364dc7cfc36ec9e9c49ac1
