### ISSUE TITLE
Lỗi tạo biểu mẫu ở nv_form

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/module-nvform#18]
Khi tạo biểu mới ở nv_form ấn nút Submit không thêm được biểu mẫu mới

![image](https://cloud.githubusercontent.com/assets/9360175/11680130/aa2551bc-9e88-11e5-9291-463b37637234.png)

**Comment by mynukeviet** [comment]
Fixed: https://github.com/hongoctrien/module-nvform/commit/1dc30857df0ea3a96822ecc4cafe188421613a5c
