### ISSUE TITLE
Lỗi không hiên thị dữ liệu date ngoài site

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/module-nvform#2]
Ngoài site hiện tại chưa chuyển sang dữ liệu date mà vẫn còn ở dạng mã hóa số trong csdl
![date](https://cloud.githubusercontent.com/assets/13896524/9432559/05c447e6-4a4f-11e5-8cd2-b74611a21872.png)

**Comment by mynukeviet** [comment]
Fixed: https://github.com/hongoctrien/module-nvform/commit/60ec4c4f528bd41dd92f62e4afceb97de1660010
