### ISSUE TITLE
Cần chỉnh lại phần "Thay đổi câu trả lời" trong câu hỏi để tránh nhập sai và tích nhiều lần

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/module-nvform#8]
sau khi chọn và hoàn tất và không tích ô "Thay đổi câu trả lời" thì đưa ra cảnh báo "không được phép thay đổi"
![multi selebox](https://cloud.githubusercontent.com/assets/13896524/9432823/71398942-4a53-11e5-88d0-97a3771167ff.png)
"Thay đổi câu trả lời" cần mặc định là đã tích thay vì như hiện tại bắt người điền phải tích, nếu nhập 100 biểu mẫu chắc là thành cực hình

**Comment by mynukeviet** [comment]
Fixed: https://github.com/hongoctrien/module-nvform/commit/44e5ff0396afed2df89d82711b6a4e21916c17b0
