### ISSUE TITLE
Định dạng của loại dữ liệu thời gian vẫn là dãy số

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/module-nvform#9]
Hiện tại định dạng của loại dữ liệu thời gian khi xem tổng quát vẫn là dãy số chuyển đổi trong cơ sở dữ liệu chưa chuyển về thời gian thông thường

**Comment by mynukeviet** [comment]
Fixed: https://github.com/hongoctrien/module-nvform/commit/60ec4c4f528bd41dd92f62e4afceb97de1660010
